#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChessOpenings.Droid.Resource", IsApplication=true)]

namespace ChessOpenings.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BrownB = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BrownK = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BrownN = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BrownP = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int BrownQ = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int BrownR = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_bishop_black = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_bishop_white = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_frequency = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_king_black = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_king_white = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_knight_black = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_knight_white = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_pawn_black = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_pawn_white = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_queen_black = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_queen_white = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon_rook_black = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon_rook_white = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int icon_trophy = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int rightArrow = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int YellowB = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int YellowK = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int YellowN = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int YellowP = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int YellowQ = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int YellowR = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001a
			public const int arrow = 2131034138;
			
			// aapt resource value: 0x7f050003
			public const int back_one_move_button = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int boardAndButtons = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int boardLayout = 2131034113;
			
			// aapt resource value: 0x7f050014
			public const int board_fragment_container = 2131034132;
			
			// aapt resource value: 0x7f050002
			public const int buttonPanel = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int current_opening_holder = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int dataLayout = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int flip_board_button = 2131034117;
			
			// aapt resource value: 0x7f05001f
			public const int frequency_display_compact = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int iv_winrate_icon = 2131034144;
			
			// aapt resource value: 0x7f050013
			public const int main_layout = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int main_line_heading = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int main_line_layout = 2131034123;
			
			// aapt resource value: 0x7f050015
			public const int move_notation = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int next_move_list = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int next_move_tile_layout = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int openingLabel = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int openingName = 2131034121;
			
			// aapt resource value: 0x7f050017
			public const int opening_name = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int percentage = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int piece_image = 2131034137;
			
			// aapt resource value: 0x7f050004
			public const int reset_board_button = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int secondary_line_heading = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int secondary_lines_layout = 2131034126;
			
			// aapt resource value: 0x7f050018
			public const int tile = 2131034136;
			
			// aapt resource value: 0x7f05000d
			public const int tileView = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int tile_scroll_view = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int tsv = 2131034128;
			
			// aapt resource value: 0x7f05001b
			public const int tv_destination_square = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int tv_next_opening_name = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int winrate = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int winrate_heading = 2131034141;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int boardView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int next_move_table_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int next_move_tile_view = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int next_move_tile_view_compact = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
